version: '3'
services:
 app:
    build: .
    ports:
      - 80:8080
    environment:
      - SPRING_PROFILE_ACTIVE=prod
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_KEY=${JWT_KEY}


    depends_on:
      db:
        # This is important! Without it application will fail because Postgres has not started properly!
        condition: service_healthy


 db:
    image: postgres
    restart: always
    environment:
    - POSTGRES_USER=${POSTGRES_USERNAME}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${DATABASE_NAME}
    ports:
    - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5